### ISSUE TITLE
Creating environment using environment.yml caused the following errors, can you help me to resolve?

### ISSUE THREAD

**Issue by ayyappa1993** [subhc/SPNet#3]
Pip subprocess error:
twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
jupyter-console 6.0.0 has requirement prompt_toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.
ipython 7.4.0 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.
boto3 1.8.2 has requirement botocore<1.12.0,>=1.11.2, but you'll have botocore 1.12.62 which is incompatible.
allennlp 0.7.2 has requirement pytz==2017.3, but you'll have pytz 2018.5 which is incompatible.
Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by subhc** [comment]
Hi that was an environment dump by conda. I am not sure why that is giving a problem. Try with this [environment.zip](https://github.com/subhc/SPNet/files/4000644/environment.zip). 
Otherwise you can try running the code from an empty environment and keep adding the packages it errors missing with the specific version mentioned in the environment.yaml file. That generally works.
